
[[value-type-list]]
==== LIST

Properties and parameters *MAY* specify its value to be an unordered list
of values. There is no
significance to the order of values in a list.

This construct is called the "LIST". Each value in the LIST *MUST* have the same
value type.

===== Syntax

The `LIST(value-type)` notation is used to describe this value type, of
a list of elements, where each of its elements is of value type `value-type`.


[[value-type-list-example1]]
===== Example 1

The "NICKNAME" property of <<RFC6350>> defines its value to be an
unordered list of TEXT.

In vObject notation its value type is defined to be:

[source,abnf]
----
LIST(TEXT)
----

[[value-type-list-example2]]
===== Example 2

The "RECUR" property of <<RFC5545>> defines its value to be an
unordered list of ASSIGN.

In vObject notation its value type is defined to be:

[source,abnf]
----
LIST(KEYVALUE, ";")
----


===== Normalizing a LIST

When normalizing a LIST, each value of it *MUST* be normalized,
and the values *MUST* be sorted alphabetically.

For example, values of <<RFC5545>> RESOURCES, FREEBUSY, EXDATE, RDATE,
CATEGORIES, *MUST* be sorted alphabetically when normalized.


////

By default, the following basic value types accept LIST input

6350: DATE, TIME, DATE-TIME, DATE-AND-OR-TIME, and TIMESTAMP
TEXT multivalue comma
integer
float

5545
- value types: date, date-time, duration, float, integer, period, text, time

////

