= Internet-Draft: CalConnect vObject Model and vFormat Syntax

image:https://github.com/CalConnect/csd-vobject-vformat/workflows/docker/badge.svg["Build Status", link="https://github.com/CalConnect/csd-vobject-vformat/actions?workflow=docker"]

This document is available in its rendered forms here:

* https://CalConnect.github.io/csd-vobject-vformat/[HTML]


== Fetching the document

[source,sh]
----
git clone https://github.com/CalConnect/csd-vobject-vformat/
----

== Installing Build Tools

See https://www.metanorma.com/author/topics/install/


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker:

[source,sh]
----
docker run -v "$(pwd)":/metanorma -w /metanorma -it metanorma/mn metanorma site generate --agree-to-terms
----


== Building The Document

[source,sh]
----
metanorma site generate --agree-to-terms
----

The generated documents are accessible under `site/`.


== Iterating the document

[source,sh]
----
metanorma site generate --agree-to-terms
open site/index.html
----


== Checking Against idnits

https://tools.ietf.org/tools/idnits/[idnits] is the RFC checking tool prior to
submissions.

The `make` target finds exactly the document name from the `:name:` document
attribute and puts the file in the right place before calling `idnits` to
prevent it complaining about the location.

[source,sh]
----
idnits draft-calconnect-vobject-vformat.nits
----

