== Existing Property Data Type Mapping

=== RFC 6350 Property Mapping

Properties with the default data type as TEXT.

Property | Default Data Type | Alt. Data Types | Original Data Type
:--------|:-----|:----|:----
BEGIN | TEXT |  | 1\*TEXT
END   | TEXT |  | 1\*TEXT
KIND  | TEXT |  | 1\*TEXT
XML   | TEXT |  | 1\*TEXT
FN    | TEXT |  | 1\*TEXT
BDAY  | ISO-DATE-AND-OR-TIME | TEXT | 1\*date-and-or-time, 1\*text
ANNIVERSARY | ISO-DATE-AND-OR-TIME | TEXT | 1\*date-and-or-time, 1\*text
EMAIL | TEXT | | 1\*TEXT,
TZ | TEXT | URI, ISO-UTC-OFFSET | 1\*TEXT, URI, UTC-OFFSET
TITLE | TEXT | | 1\*TEXT
ROLE | TEXT | | 1\*TEXT
NOTE | TEXT | | 1\*TEXT
PRODID | TEXT | | 1\*TEXT
VERSION | TEXT | | 1\*TEXT

Properties with the default data type as URI.

Property | Default Data Type | Alt. Data Types | Original Data Type
:--------|:-----|:----|:----
TEL | URI | TEXT | 1\*text, URI
SOURCE | URI |  | URI
PHOTO | URI |  | URI
IMPP | URI |  | URI
GEO | URI |  | URI
LOGO | URI |  | URI
MEMBER | URI |  | URI
RELATED | URI | TEXT | URI, 1\*text
UID | URI |  | URI, 1\*text
KEY | URI |  | URI, 1\*text
SOUND | URI |  | URI
URL | URI |  | URI
FBURL | URI |  | URI
CALADRURI | URI |  | URI
CALURI | URI |  | URI


Properties with FIELDSET.

Property | Default Data Type | Alt. Data Types | Original Data Type
:--------|:-----|:----|:----
N | FIELDSET(5\*LIST(TEXT)) | | TEXT
GENDER | FIELDSET(2\*TEXT) | | TEXT
ADR | FIELDSET(7\*LIST(TEXT)) | | TEXT
ORG | FIELDSET(1\*TEXT) | | TEXT
CLIENTPIDMAP | FIELDSET(INTEGER-64, URI) | | TEXT


////
6350 N: structured text, ordered list split by ";". A single structured text value. Each component can have multiple values.
6350 GENDER: structured text with two components. each component is text., split by ";"
6350 ADR: structured text, separated by ";"
6350 ORG: structured text split by ";"
6350 CLIENTPIDMAP: semicolon-separated pair of values, first is integer, second is uri

////

Properties with LIST.

Property | Default Data Type | Alt. Data Types | Original Data Type
:--------|:-----|:----|:----
NICKNAME | LIST(TEXT) | | TEXT
CATEGORIES | LIST(TEXT) | | TEXT


Properties with ISO-DATE-AND-OR-TIME.

Property | Default Data Type | Alt. Data Types | Original Data Type
:--------|:-----|:----|:----
BDAY | ISO-DATE-AND-OR-TIME | TEXT | date-and-or-time, text
ANNIVERSARY | ISO-DATE-AND-OR-TIME | TEXT | date-and-or-time, text


Properties with ISO-DATE-TIME-COMPLETE.

Property | Default Data Type | Alt. Data Types | Original Data Type
:--------|:-----|:----|:----
REV | ISO-DATE-TIME-COMPLETE | | timestamp


Properties with LANGUAGE-TAG.

Property | Default Data Type | Alt. Data Types | Original Data Type
:--------|:-----|:----|:----
LANG | LANGUAGE-TAG | | language-tag



=== RFC 5545 Property Mapping

Properties with the default data type as TEXT.

Property | Default Data Type | Alt. Data Types | Original Data Type
:--------|:-----|:----|:----
CALSCALE | TEXT | | 1\*TEXT
METHOD | TEXT | | 1\*TEXT
PRODID | TEXT | | 1\*TEXT
VERSION | TEXT | | 1\*TEXT
CLASS | TEXT | | 1\*TEXT
COMMENT | TEXT | | 1\*TEXT
DESCRIPTION | TEXT | | 1\*TEXT
LOCATION | TEXT | | 1\*TEXT
STATUS | TEXT | | 1\*TEXT
SUMMARY | TEXT | | 1\*TEXT
TRANSP | TEXT | | 1\*TEXT
TZID | TEXT | | 1\*TEXT
TZNAME | TEXT | | 1\*TEXT
CONTACT | TEXT | | 1\*TEXT
RELATED-TO | TEXT | | 1\*TEXT
UID | TEXT | | 1\*TEXT
ACTION | TEXT | | 1\*TEXT
IANA-REGed/X- | TEXT | | 1\*TEXT
REQUEST-STATUS | TEXT | | 1\*TEXT



Properties with the default data type as URI.

Property | Default Data Type | Alt. Data Types | Original Data Type
:--------|:-----|:----|:----
ATTACH | URI | BINARY | URI, BINARY
TZURL | URI |  | URI
URL | URI |  | URI
ATTENDEE | URI | | cal-address
ORGANIZER | URI | | cal-address



Properties with FIELDSET.

Property | Default Data Type | Alt. Data Types | Original Data Type
:--------|:-----|:----|:----
GEO | FIELDSET(2\*FLOAT) | | FLOAT ";" FLOAT


Properties with LIST.

Property | Default Data Type | Alt. Data Types | Original Data Type
:--------|:-----|:----|:----
CATEGORIES | LIST(TEXT) | | TEXT
RESOURCES | LIST(TEXT) | | TEXT


Properties with CAL-INTERVAL.

Property | Default Data Type | Alt. Data Types | Original Data Type
:--------|:-----|:----|:----
FREEBUSY | LIST(CAL-INTERVAL) | | LIST(PERIOD)


Properties with ISO-DATE-TIME-BASIC.

Property | Default Data Type | Alt. Data Types | Original Data Type
:--------|:-----|:----|:----
COMPLETED | ISO-DATE-TIME-BASIC | | DATE-TIME
CREATED | ISO-DATE-TIME-BASIC | | DATE-TIME
DTSTAMP | ISO-DATE-TIME-BASIC | | DATE-TIME
LAST-MODIFIED | ISO-DATE-TIME-BASIC | | DATE-TIME
DTEND | ISO-DATE-TIME-BASIC | ISO-DATE-COMPLETE | DATE-TIME, DATE
DUE | ISO-DATE-TIME-BASIC | ISO-DATE-COMPLETE | DATE-TIME, DATE
DTSTART | ISO-DATE-TIME-BASIC | ISO-DATE-COMPLETE | DATE-TIME, DATE
RECURRENCE-ID | ISO-DATE-TIME-BASIC | ISO-DATE-COMPLETE | DATE-TIME, DATE


Properties with LIST.

Property | Default Data Type | Alt. Data Types | Original Data Type
:--------|:-----|:----|:----
EXDATE | LIST( ISO-DATE-TIME-BASIC / ISO-DATE-COMPLETE ) | | DATE-TIME, DATE
RDATE | LIST( ISO-DATE-TIME-BASIC / ISO-DATE-COMPLETE / CAL-INTERVAL) | | DATE-TIME, DATE, PERIOD


Properties with INTEGER.

Property | Default Data Type | Alt. Data Types | Original Data Type
:--------|:-----|:----|:----
PERCENT-COMPLETE | INTEGER-32 | | INTEGER
PRIORITY | INTEGER-32 | | INTEGER
SEQUENCE | INTEGER-32 | | INTEGER
REPEAT | INTEGER-32 | | INTEGER



Properties with DURATION.

Property | Default Data Type | Alt. Data Types | Original Data Type
:--------|:-----|:----|:----
DURATION | DURATION | | DURATION
TRIGGER | DURATION | ISO-DATE-TIME-BASIC | DURATION, DATE-TIME


Properties with CAL-UTC-OFFSET.

Property | Default Data Type | Alt. Data Types | Original Data Type
:--------|:-----|:----|:----
TZOFFSETFROM | CAL-UTC-OFFSET | | UTC-OFFSET
TZOFFSETTO | CAL-UTC-OFFSET | | UTC-OFFSET


RRULE uses the RECUR data value type, which is a special construct
defined in <<RFC5545>> with no equivalent in this document.

