
[[vobject]]
== vObject Data Model

The vObject data model is the generalized data model behind
vCard <<RFC6350>> and iCalendar <<RFC5545>>.

Both vCard <<RFC6350>> and iCalendar <<RFC5545>> data formats belong to a
family defined here as "vFormat". The "vFormat" format is a generalized data
format of both vCard and iCalendar standards, and both these formats adhere
to the vFormat requirements.

=== vObject compliant models

These formats are vObject "compliant formats" as they adhere to the rules of vObject:

* vCard version 4.0 <<RFC6350>>: the VCARD component
* Internet Calendaring and Scheduling Core Object Specification
  (iCalendar) <<RFC5545>>, the VCALENDAR, VEVENT, VJOURNAL, VFREEBUSY,
  VTIMEZONE, VALARM, VTODO, STANDARD, DAYLIGHT components
* Calendar Availability Extensions <<RFC7953>>: the VAVAILABILITY,
  AVAILABLE components
* iCalendar Patching <<VPATCH>>: the VPATCH component


=== Elements

Data within a vObject is arranged through a hierarchy that is composed of
the following elements:

* component;
* property;
* property parameter;
* property value;
* property parameter value; and
* property group.

=== Equivalence

Two vObjects are considered identical in content if their normalized
forms are textually equivalent.

include::vobject/vo-component.adoc[]
include::vobject/vo-property.adoc[]
include::vobject/vo-property-value.adoc[]
include::vobject/vo-parameter.adoc[]
include::vobject/vo-parameter-value.adoc[]
include::vobject/vo-group.adoc[]

