
[[vobject]]
== vObject Data Model

The vObject data model is the generalized data model from the implied
data models of vCard <<RFC6350>> and iCalendar <<RFC5545>>.

While both vCard <<RFC6350>> and iCalendar <<RFC5545>> specify data formats for different purposes,
the data model behind them follow an identical logical structure (using
components, properties and parameters) with similar requirements.

By creating a generalized data model ("vObject") that is compatible with both,
we are able to ensure that newly developed data modification techniques
for vObject would be interoperable on all other vObject-compliant models.

=== vObject-compliant models

The implied data models behind these formats are compliant to the vObject data model:

* vCard version 4.0 <<RFC6350>>: the VCARD component
* Internet Calendaring and Scheduling Core Object Specification
  (iCalendar) <<RFC5545>>, the VCALENDAR, VEVENT, VJOURNAL, VFREEBUSY,
  VTIMEZONE, VALARM, VTODO, STANDARD, DAYLIGHT components
* Calendar Availability Extensions <<RFC7953>>: the VAVAILABILITY,
  AVAILABLE components
* iCalendar Patching <<VPATCH>>: the VPATCH component


=== Elements

Data within a vObject is arranged through a logical hierarchy composed of
the following elements:

* component;
* property;
* property parameter;
* property value;
* property parameter value; and
* property group.

=== Equivalence

Two vObjects are considered identical in content if their normalized
forms are textually equivalent.

include::vobject/vo-component.adoc[]
include::vobject/vo-property.adoc[]
include::vobject/vo-property-value.adoc[]
include::vobject/vo-parameter.adoc[]
include::vobject/vo-parameter-value.adoc[]
include::vobject/vo-group.adoc[]

