
[[vformat]]
== vFormat Syntax

The "vFormat" format is the generalized syntax from the vCard <<RFC6350>>
and iCalendar <<RFC5545>> formats, and is the native format for vObject
serialization ("vObject native format").

vFormat is called the "native" format for vObjects to distinguish it from
alternative representations of vObject data, such as their XML (xCal, xCard)
or JSON (jCal, jCard) representations.

Its syntax originated from the textual representation of the iCalendar
and vCard formats, and is mostly traceable back to the original vCard
and iCalendar specifications <<vCard21>>.

Both of these formats are considered "instances" (or "downstream formats")
of vFormat, and fully adhere to vFormat requirements.

Parsing and modification operations that work on vFormat *SHOULD* work on
all its instances, including iCalendar <<RFC5545>> and vCard <<RFC6350>>.


include::vformat/vf-abnf.adoc[]
include::vformat/vf-component.adoc[]
include::vformat/vf-property.adoc[]
include::vformat/vf-property-value.adoc[]
include::vformat/vf-parameter.adoc[]
include::vformat/vf-parameter-value.adoc[]
include::vformat/vf-group.adoc[]

