
[[normalization]]
== Normalization

A normalization procedure can be applied to vObjects (in its various
representations) to make them compatible prior to comparison, allowing
for consistent results. The result of normalization processing of a
vObject, is an equivalent vObject described according to vFormat
representation.

The normalization method has the following properties:

* stable across different implementations generating the same output
  from the same input
* compatible with alternative representation formats such as xCard
  <<RFC6351>> / jCard <<RFC7095>> and xCal <<RFC6321>> / jCal <<RFC7265>>
* generates output adhering to the original vObject format allowing
  interoperability with existing implementations
* generates output compatible with protocols that utilize these
  vObject, such as CardDAV <<RFC6352>> and CalDAV <<RFC4791>> systems.

There are two levels of normalization.

* vObject normalization, of values and property parameter values, are performed
  within the vObject data model;

* vFormat normalization, of the format syntax itself, is performed
  during serialization of a vObject into vFormat.

=== Approach

The goals of the normalization procedure are:

* A normalized vObject will be a valid vObject in vFormat syntax.
  Therefore the normalization procedure requires
  knowledge of the source specific vObject format.

* A normalized vObject is stable across alternative representation
  formats, such as xCal and jCal of iCalendar, and xCard and jCard of
  vCard. This allows comparison of vObject content regardless of the
  representation format.

* Allows comparison of equivalence of content rather than formatting.
  E.g., addition of new-lines within a vCard and order of listed
  properties do not affect the resulting normalized form.

* A normalized vObject *MUST* maintain validity under the original
  format rules, such as in the case of VCARD <<RFC6350>> components,
  the "VERSION" property line *MUST* be located immediately after
  the "BEGIN" property line.

=== Steps

In order to serialize a vObject into normalized vFormat syntax,
one would directly serialize the vObject data model into vFormat syntax.

The steps are generally described below.

. Normalize the vObject

.. Normalize properties

... Normalize property parameters

.... Normalize property parameter types

.... Normalize property parameter values

..... Sort property parameter values alphabetically.

..... Concatenate property parameter values.

.... Normalize property parameter key: cast to uppercase.

.... Concatenate string form of property parameter key, value type
       and values.

... Normalize property values

.. Normalize inner vObjects (sub-components)

... Perform the same function as (1)


=== Alternative vCard representations

The normalization procedure applies to alternative vObject
representations as well, including:

* xCard <<RFC6351>>
* jCard <<RFC7095>>
* xCal <<RFC6321>>
* jCal <<RFC7265>>

To normalize a vObject provided in these representations, the
vObject data should be first normalized in data model form
according to <<vobject>>, and then serialized into these representations.

