
[[caldav]]
== CalDAV

=== Additional Server Semantics for PUT, COPY and MOVE

This specification creates an additional precondition and postcondition
for the PUT, COPY, and MOVE methods when:

* A PUT operation of a calendar object resource into a calendar
  collection occurs <<RFC4791>>;

* A COPY or MOVE operation of a calendar object resource into a
  calendar collection occurs <<RFC4791>>; and

* A COPY or MOVE operation occurs on a calendar collection <<RFC4791>>.

// TODO: anything we need to do with Scheduling <<RFC6638>>?

==== Provide Normalized Output

Certain servers perform silent changes or cleanups of client provided
iCalendar data when stored as calendar object resources, such as the order of
property parameters or scrubbed values.

The resulting iCalendar data stored on the server (and when returned back to
the client) *MAY* end up different than that of the client without its
knowledge. It is therefore necessary for the client to be reported on
such modifications.

Additional Postcondition:

[source]
----
(CALDAV:resource-normalized): Convert to normalized format.
----
