
[[mapping-rfc-data-value-types]]
== Mapping Of Data Value Types For Existing RFCs

The vObject value types in this section are described using
vObject value type notation (see <<vo-value-type-notation>>).

=== RFC 6350

|===
| vObject Value Type  | Original Value Type

| BOOLEAN              | BOOLEAN
| ISO-DATE-FLEX        | DATE
| ISO-DATE-AND-OR-TIME | DATE-AND-OR-TIME
| ISO-DATE-TIME-FLEX   | DATE-TIME
| FLOAT                | FLOAT
| INTEGER-64           | INTEGER
| LANGUAGE-TAG         | LANGUAGE-TAG
| TEXT                 | TEXT
| ISO-TIME-FLEX        | TIME
| ISO-TIME-COMPLETE    | TIMESTAMP
| URI                  | URI
| ISO-UTC-OFFSET       | UTC-OFFSET

|===


=== RFC 5545

|===
| vObject Value Type | Original Value Type

| BINARY              | BINARY
| BOOLEAN             | BOOLEAN
| URI                 | CAL-ADDRESS
| ISO-DATE-COMPLETE   | DATE
| ISO-DATE-TIME-BASIC | DATE-TIME
| CAL-DURATION        | DURATION
| FLOAT               | FLOAT
| INTEGER-32          | INTEGER
| CAL-DURATION        | PERIOD
| TEXT                | TEXT
| ISO-TIME-BASIC      | TIME
| URI                 | URI
| CAL-UTC-OFFSET      | UTC-OFFSET
| RECURMAP (<<recurmap>>)   | RECUR

|===

[[recurmap]]
==== RECURMAP

RECURMAP is shown here instead of within the tables due to space constraints.

It is defined to be the value type of the following vObject value type:

[source]
----
RECURMAP = MAP(
  KEYVALUE(FREQ, TEXT),
  KEYVALUE(UNTIL, ISO-DATE-COMPLETE / ISO-DATE-TIME-BASIC),
  KEYVALUE(COUNT, INTEGER),
  KEYVALUE(INTERVAL, INTEGER),
  KEYVALUE(BYSECOND, LIST(INTEGER)),
  KEYVALUE(BYMINUTE, LIST(INTEGER)),
  KEYVALUE(BYHOUR, LIST(INTEGER)),
  KEYVALUE(BYDAY, LIST(INTEGER)),
  KEYVALUE(BYMONTHDAY, LIST(INTEGER)),
  KEYVALUE(BYYEARDAY, LIST(INTEGER)),
  KEYVALUE(BYWEEKNO, LIST(INTEGER)),
  KEYVALUE(BYMONTH, LIST(INTEGER)),
  KEYVALUE(BYSETPOS, INTEGER),
  KEYVALUE(WKST, TEXT)
)
----
