
==== ISO-TIME-BASIC

This corresponds to the TIME value type in <<RFC5545,3.3.12>>.

// This does not allow a UTC offset, not directly used but in date-time

===== Value Name

ISO-TIME-BASIC

===== Purpose

Representation of a complete time of day disallowing a UTC offset <<ISO.8601.2004>>.

===== Format Definition


[source,abnf]
----
iso-time-basic = iso-time-hour iso-time-minute iso-time-second
                 [iso-time-utc]
----

===== Description

This value format is similar to "TIME" except it disallows the additional UTC offset,
(the basic formats of <<ISO.8601.2004,4.2.5.2>>
"Local time and the difference from UTC").

This value format accepts a time of day value specified as:

* "hhmmss", the basic format of <<ISO.8601.2004,4.2.2.2>> "Complete representations".
* "hhmmssZ", the first basic format of <<ISO.8601.2004,4.2.4>> "UTC of day".

The seconds value of 60 *MUST* only be used to account for positive "leap" seconds.
Fractions of a second are not supported by this format.

This value indicates "local time" as specified in <<ISO.8601.2004,2.1.16>>.
To indicate UTC time, a "Z" character *MUST* be appended to the basic
format as described in <<ISO.8601.2004,4.2.4>> "UTC of day".

// TODO EXAMPLES

Example:

* 232050
* 232050Z

===== Normalization

No normalization procedures are needed.
