==== ISO-TIME-FLEX

// This is TIME in 6350, not directly used but for date-and-or-time

===== Value Name

ISO-TIME-FLEX

===== Purpose

This value type defines a time of day format that allows a entry of a
complete time of day <<ISO.8601.2004>>, a reduced accuracy date <<ISO.8601.2004>>
and a truncated date representation <<ISO.8601.2000>>.

===== Format Definition


[source,abnf]
----
iso-time-flex = iso-time /
                iso-time-reduced /
                iso-time-truncated

iso-time-zone = iso-time-utc / iso-time-utc-offset

iso-time-reduced =  iso-time-reduced-hour-minute /
                    iso-time-hour

iso-time-reduced-hour-minute = iso-time-hour iso-time-minute

iso-time-truncated =  iso-time-truncated-minute-second /
                      iso-time-truncated-minute-only /
                      iso-time-truncated-second-only
iso-time-truncated-minute-second = "-" iso-time-minute iso-time-second
iso-time-truncated-minute-only = "-" iso-time-minute
iso-time-truncated-second-only = "--" iso-time-second
----

===== Description

This value format accepts:

* a complete time of day, specified in <<ISO.8601.2004>> Section 4.2.2.2 "Complete representations",
* a reduced accuracy time of day, specified in <<ISO.8601.2004>> Section 4.2.2.3 "Representations with reduced accuracy",
* and a truncated representation time of day, specified in <<ISO.8601.2000>> Section 5.3.1.4 "Truncated representations".

The value can be represented in these ways:

* "hhmmss" Complete representation basic format, specified in <<ISO.8601.2004>> 4.2.2.2.
* "hhmm" Reduced accuracy representation basic format for a specific hour and minute, specified in <<ISO.8601.2004>> 4.2.2.3 a).
* "hh" Reduced accuracy representation basic format for a specific hour, specified in <<ISO.8601.2004>> 4.2.2.3 b).
* "-mmss" Truncated representation for a specific minute and second of the implied hour, specified in <<ISO.8601.2000>> Sections 5.3.1.4 a).
* "-mm" Truncated representation for a specific minute of the implied hour, specified in <<ISO.8601.2000>> Sections 5.3.1.4 b).
* "--ss" Truncated representation for a specific second of the implied minute, specified in <<ISO.8601.2000>> Sections 5.3.1.4 c).

The seconds value of 60 *MUST* only be used to account for positive "leap" seconds.
Fractions of a second are not supported by this format.

This value indicates "local time" as specified in <<ISO.8601.2004>> 2.1.16.
To indicate UTC time, a "Z" character *MUST* be appended to the basic
format as described in <<ISO.8601.2004>> Section 4.2.4 "UTC of day".

This format requires the midnight hour to be represented by "00" (<<ISO.8601.2004>>, Section 4.2.3 a)), not "24" (<<ISO.8601.2004>>, Section 4.2.3 b)).

This format supports the specificiation of UTC offsets for the
complete representation basic format
(defined in <<ISO.8601.2004>>, Section 4.2.5.2 basic format),
in the form of "hhmmss±HHMM".
"HHMM" is the hour and minute of UTC offset, defined in
<<ISO.8601.2004>>, Section 4.2.5.1 basic format.

Example:

* 102200
* 1022
* 10
* -2200
* --00
* 102200Z
* 102200+0800


===== Normalization

No normalization procedures are needed.

