
==== ISO-UTC-OFFSET

This corresponds to the UTC-OFFSET value type in <<RFC6350,4.7>>.

// The 6350's UTC-OFFSET supports "hh" but not 5545's "hhmmss"
// 5545 supports hhmm and hhmmss, but 6350 supports hhmm and hh


===== Value Name

ISO-UTC-OFFSET

===== Purpose

Representation of a UTC offset as described in <<ISO.8601.2004>>.

===== Format Definition


[source,abnf]
----
sign = "+" / "-"
iso-utc-offset = sign iso-time-hour [iso-time-minute]
----

Description:

The value can be represented in two ways:

* "±hhmm" specified in
  <<ISO.8601.2004,4.2.5.1>> "Difference between local time and UTC of day",
  the first basic format.
* "±hh" specified in
  <<ISO.8601.2004,4.2.5.1>> "Difference between local time and UTC of day",
  the second basic format.

The PLUS SIGN character MUST be specified for positive
UTC offsets (i.e., ahead of UTC).  The HYPHEN-MINUS character MUST
be specified for negative UTC offsets (i.e., behind of UTC).

The value of "-00" and "-0000" are not allowed. The time-minute,
if present, MUST NOT be 60; if absent, it defaults to zero.

////
 From 6350:
  The value type is an offset from Coordinated Universal Time (UTC).
   It is specified as a positive or negative difference in units of
   hours and minutes (e.g., +hhmm).  The time is specified as a 24-hour
   clock.  Hour values are from 00 to 23, and minute values are from 00
   to 59.  Hour and minutes are 2 digits with high-order zeroes required
   to maintain digit count.  The basic format for ISO 8601 UTC offsets
   MUST be used.

////

===== Example

The following UTC offsets are given for standard time for
New York (five hours behind UTC) and Geneva (one hour ahead of
UTC):

* -05
* -0500
* +01
* +0100


===== Normalization

No normalization procedures are needed.
