
[[value-type-fieldset]]
==== FIELDSET

Some properties and parameters require values defined in terms of multiple parts.

This construct of multiple structured values is called a "FIELDSET".
Each value in FIELDSET *MUST* have the same value type as defined.

===== Value Type Notation

When used to describe a value type, the `FIELDSET(field-1-value-type, ...)` notation
is defined as a structure of fields separated by the SEMICOLON character, where each
of its fields is of value type `field-i-value-type`, where `i` represents the index
of the specific field.

[[value-type-fieldset-example1]]
===== Example 1

The "CLIENTPIDMAP" property of <<RFC6350>> takes a tuple of "INTEGER" and "URI".

The notation in vObject given for its value type would be this
indicating that the first value is an INTEGER, while the latter value
is a URI:

[source,abnf]
----
FIELDSET(INTEGER, URI)
----

[[value-type-fieldset-example2]]
===== Example 2

The "N" property of <<RFC6350>> defines its value of having 5 values at once, and
each of these values are a LIST of TEXT.

The notation in vObject given for its value type would be this
indicating that there are 5 fields in this FIELDSET,
and each value element of it *MUST* be a LIST of TEXT elements:

[source,abnf]
----
FIELDSET(5\*LIST(TEXT))
----

===== Normalizing a FIELDSET

When normalizing a FIELDSET, each value *MUST* have been normalized,
but the order of FIELDSET elements *MUST NOT* be rearranged.
