
[[vformat-value-types]]
=== Value Types

Most vObject value types (<<vobject-property-value-types>>) can be serialized
into vFormat syntax natively. However, some considerations exist for certain
value types, as described below.


==== TEXT

===== vFormat Definition

[source,abnf]
----
text = *(TSAFE-CHAR / ":" / DQUOTE / ESCAPED-CHAR)
  ; Folded according to description above

ESCAPED-CHAR = ("\\" / "\;" / "\," / "\N" / "\n")
  ; \\ encodes \, \N or \n encodes newline
  ; \; encodes ;, \, encodes ,

TSAFE-CHAR = WSP / %x21 / %x23-2B / %x2D-39 / %x3C-5B /
            %x5D-7E / NON-US-ASCII
  ; Any character except CONTROLs not needed by the current
  ; character set, DQUOTE, ";", ":", "\", ","
----

===== Description

For historic reasons, the COMMA and SEMICOLON characters *MUST*
be escaped with a preceding BACKSLASH character (U+005C). The historic usage
of the "text" value type accepting multiple values *MUST NOT* be used unless
the multiple values are provided through a LIST.

An intentional line break *MUST* be represented by the sequence of "\n" or "\N"
(BACKSLASH followed by a LATIN SMALL LETTER N (U+006E) or
a LATIN CAPITAL LETTER N (U+004E)).

===== Example

The vFormat value for <<value-type-text-example>>
requires application of the following formatting rules:

* representing line breaks as "\n"
* line folding with CRLF and the folded-line beginning with a single space
* escaping of the COMMA character

and therefore *SHOULD* be represented as:

----
NOTE:TC VCARD\nThe Calendaring And Scheduling Consortium\nJuly 20\, 2017
----

===== Normalization

Values of the TEXT data type *MUST* convert all line breaks ("\n" or "\N")
into the character sequence "\n" (BACKSLASH followed by a LATIN SMALL LETTER N
(U+006E)).




==== KEYVALUE

In the vFormat implementation of `KEYVALUE`, the EQUAL sign character (`=`) is used
to delimit the separation between `assign-key` and `assign-value`.

Therefore, the value of `KEYVALUE` *MUST NOT* contain the unescaped EQUAL sign
character for the avoidance of doubt.

===== Examples

* `FREQ=WEEKLY`
* `BYHOUR=3,6,9`
* `BYWEEKNO=MO,TU,WE,TH,FR,SA`



==== FIELDSET

In vFormat syntax, FIELDSET field <<value-type-fieldset>>
property values *MUST* have their value parts separated by a
SEMICOLON character, and all elements
*MUST NOT* contain an unescaped the SEMICOLON character to prevent
breaking of the FIELDSET syntax.

===== Example

<<value-type-fieldset-example1>> provides the value definition of the
"CLIENTPIDMAP" property of <<RFC6350>>, which
takes a tuple of "INTEGER" and "URI" separated by a SEMICOLON.

An example value in vFormat notation is given below:

[source]
----
1;urn:uuid:3df403f4-5924-4bb7-b077-3c711d9eb34b
----



==== LIST

In vFormat syntax, values in a list of values *MUST* be separated by a
delimiting character. The default delimiter character is the COMMA character.
An element within any LIST element *MUST NOT* contain
an unescaped delimiter character to prevent breaking of the LIST syntax.

By default, the `LIST(value-type)` function denotes a list of elements separated
by the COMMA character.

===== Alternative Delimitation

A property *MAY* specify that its LIST elements are delimited by another character
other than the COMMA, for example, the `RECUR` property of <<RFC5545>> uses
the SEMICOLON character as a delimiter. This is allowed when explicitly specified in
the defining syntax, given the restriction that any element within does not
contain an unescaped delimiter character (i.e., in this case, the SEMICOLON).

In the case where a delimiter character for the LIST is not a COMMA, the
`LIST(value-type, delimiter)` syntax is used to define the delimiter,
where each of its elements is of value type `value-type`, and the delimiting
character is specified to be `delimiter`.

===== Example 1

In <<value-type-list-example1>>, the "NICKNAME" property of <<RFC6350>>
defines its value to be an unordered list of TEXT, delimited by a COMMA.

An example in vFormat syntax is provided below:

[source,abnf]
----
Tom,Tommy,Thomas
----


===== Example 2

In the definition of <<value-type-list-example2>>,
the "RECUR" property of <<RFC5545>> defines its value to be an
unordered list of ASSIGN, separated by the SEMICOLON character.

An example in vFormat syntax is provided below:

[source,abnf]
----
FREQ=MONTHLY;BYDAY=MO,TU,WE,TH,FR;BYSETPOS=-1
----


==== MAP

In vFormat syntax, as with `LIST`, values in a list of values *MUST* be separated
by a delimiting character. The default delimiter character is the SEMICOLON character.
An element within any `MAP` element *MUST NOT* contain
an unescaped delimiter character to prevent breaking of the `MAP` syntax.

===== Syntax

In the case where a delimiter character for the MAP is not a SEMICOLON, the
`MAP(delimiter, kv_1, kv_2)` syntax is used to define the delimiter,
where each of its elements is of value type KEYVALUE, and the delimiting
character is specified to be `delimiter`.

===== Example

The MAP definition in <<value-type-map-example>> utilizes the
SEMICOLON character as delimiter.

An example value of the it, obtained from <<RFC5545,clause 3.3.10>>,
is reproduced below for the reader's convenience:

[source]
----
FREQ=YEARLY;INTERVAL=2;BYMONTH=1;BYDAY=SU;BYHOUR=8,9;BYMINUTE=30
----

